# Generated by Django 5.1.2 on 2024-11-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('car_model', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('rental_date', models.DateField()),
                ('return_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('model_year', models.PositiveIntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('mileage', models.PositiveIntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
