# Generated by Django 5.1.2 on 2024-10-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonrides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('car_model', models.CharField(max_length=100)),
                ('booking_date', models.DateField()),
                ('rental_duration', models.PositiveIntegerField(help_text='Duration in days')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
