# Generated by Django 5.1.3 on 2024-11-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonrides', '0002_carbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('model_year', models.PositiveIntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('mileage', models.PositiveIntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
